Disable artifacts passing from build stage to test-builds
When the build artifacts are passed from the primary build stage
to the test-builds they will fail because gbp finds the already
existing artifacts and thinks they are untracked files, failing
the build.

gbp:info: Fetching from default remote for each branch
gbp:info: Found detached head at '335660c92dfcf0a2f8916d6f234f33455d045aa9'
gbp:error: You have uncommitted changes in your source tree:
gbp:error: HEAD detached at 335660c9
Untracked files:
  (use "git add <file>..." to include in what will be committed)

 debian/output/

nothing added to commit but untracked files present (use "git add" to track)

ERROR: Job failed: exit code 1

Solution is to clear the dependencies of the job:

See https://docs.gitlab.com/ee/ci/yaml/#dependencies
    "Note that artifacts from all previous stages are passed by default."
    "Defining an empty array will skip downloading any artifacts for that job."