Bugfix: Don't use too new Python syntax filter-output
Fix regression from ea9086ab where Python 3.6 print formatting was applied.
It cannot be used (yet) since the backports support all the way back to
Debian Stretch, which does not have a new enough Python version, leading
to builds failing with errors like:

  File "/usr/local/bin/filter-output", line 68
    print(f'{bytes_written} {bytes_shown} {byte_counter}', file=sys.stderr)
  SyntaxError: invalid syntax