Comment add_extra_repository.sh
Because it breaks piuparts

0m23.2s ERROR: Command failed (status=1): ['chroot', '/tmp/tmpwRJsA8', 'eatmydata', 'tmp/scripts/pre_remove_50_find_bad_permissions']
  ERROR: BAD PERMISSIONS
  -rwxrwxrwx. 2 root root 1840 Aug 15 16:24 /usr/local/bin/add_extra_repository.sh

Signed-off-by: Agustin Henze <tin@debian.org>